archs/sparc: mention SIGBUS/unaligned access and link to tracker bug
gentoo/devmanual pull request #266
Opened 2022-01-22 20:50 UTC by thesamesam

Bug: https://bugs.gentoo.org/371525
Signed-off-by: Sam James <sam@gentoo.org>

2022-02-04 13:27 UTC, juippis commented on archs/sparc/text.xml
> +issues can be found <uri link="https://bugs.gentoo.org/371525">here</uri>.
```suggestion
<c>SIGBUS</c> signal to be sent to the errant process.
<uri link="https://bugs.gentoo.org/371525">A tracker bug for known
issues</uri>.
```
https://devmanual.gentoo.org/appendices/devbook-guide/index.html

> Please avoid the click here syndrome as recommended by the [W3C](https://www.w3.org/QA/Tips/noClickHere).

2022-02-06 14:05 UTC, sbraz requested changes

2022-02-06 14:05 UTC, sbraz commented on archs/sparc/text.xml
> +issues can be found <uri link="https://bugs.gentoo.org/371525">here</uri>.
```suggestion
<c>SIGBUS</c> signal to be sent to the errant process. Known issues should be
linked to <uri link="https://bugs.gentoo.org/371525">the related tracker bug</uri>.
```

2022-02-21 05:14 UTC, thesamesam commented on archs/sparc/text.xml
> +issues can be found <uri link="https://bugs.gentoo.org/371525">here</uri>.
Thanks!

2022-02-21 05:15 UTC, closed without merging